apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust301097871451505698
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster1/context/301097871451505698
  prune: true
  sourceRef:
    kind: GitRepository
    name: "301097871451505698"
  targetNamespace: default
status: {}
