apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4563464879536565766
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster1/context/4563464879536565766
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4563464879536565766"
  targetNamespace: default
status: {}
